export const data = JSON.parse("{\"key\":\"v-456050bc\",\"path\":\"/zh/development/fontend/%E4%B8%89%E5%A4%A7%E7%BB%84%E4%BB%B6/3-%E5%8E%9F%E5%AD%90%E7%BB%84%E4%BB%B6/customize-atomic-comp.html\",\"title\":\"动手写一个原子组件\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"动手写一个原子组件\",\"icon\":\"page\",\"order\":1,\"author\":\"gd\",\"date\":\"2022-09-07T00:00:00.000Z\",\"category\":[\"二次开发\"],\"tag\":[\"简介\",\"前端\",\"二次开发\"],\"sticky\":true,\"star\":true,\"footer\":\"这是测试显示的页脚\",\"copyright\":\"优速搭 版权所有\",\"summary\":\"前置知识 原子组件：一种可以在CRUD容器内渲染的基础组件，且由于CRUD容器分为 数组型容器(表格、循环的卡片等)、对象型容器(表单)，所以原子组件也必须兼容数组型和对象型。 动手写一个原子组件 在线编写原子组件 打开在线Coding界面 按照下图操作：打开开发平台 -> 进入组件入口 -> 选择原子组件 -> 点击在线编写组件 -> 显示如下界面。 拷贝\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-v2-demo.mrhope.site/zh/development/fontend/%E4%B8%89%E5%A4%A7%E7%BB%84%E4%BB%B6/3-%E5%8E%9F%E5%AD%90%E7%BB%84%E4%BB%B6/customize-atomic-comp.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"优速搭\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"动手写一个原子组件\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"gd\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"简介\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"二次开发\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-09-07T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-US\",\"href\":\"/development/fontend/%E4%B8%89%E5%A4%A7%E7%BB%84%E4%BB%B6/3-%E5%8E%9F%E5%AD%90%E7%BB%84%E4%BB%B6/customize-atomic-comp.html\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"前置知识\",\"slug\":\"前置知识\",\"link\":\"#前置知识\",\"children\":[]},{\"level\":2,\"title\":\"动手写一个原子组件\",\"slug\":\"动手写一个原子组件\",\"link\":\"#动手写一个原子组件\",\"children\":[{\"level\":4,\"title\":\"打开在线Coding界面\",\"slug\":\"打开在线coding界面\",\"link\":\"#打开在线coding界面\",\"children\":[]},{\"level\":4,\"title\":\"拷贝模板代码到编辑器并做相应修改\",\"slug\":\"拷贝模板代码到编辑器并做相应修改\",\"link\":\"#拷贝模板代码到编辑器并做相应修改\",\"children\":[]},{\"level\":4,\"title\":\"新建该原子组件可视化的配置文件\",\"slug\":\"新建该原子组件可视化的配置文件\",\"link\":\"#新建该原子组件可视化的配置文件\",\"children\":[]},{\"level\":4,\"title\":\"保存并上传该原子组件所有文件\",\"slug\":\"保存并上传该原子组件所有文件\",\"link\":\"#保存并上传该原子组件所有文件\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.27,\"words\":381},\"filePathRelative\":\"zh/development/fontend/三大组件/3-原子组件/customize-atomic-comp.md\",\"localizedDate\":\"2022年9月7日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
